[package]
name = "kof-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
minifb = { version = "0.23.0", features = ["wayland"] }
